### YamlMime:Role 
title: Functional Consultant 
metadata: 
  title: Functional Consultant 
  description: Les Consultants Fonctionnels tirent parti de Microsoft Dynamics 365 et de Microsoft Power Platform pour anticiper et planifier les besoins des clients. 
uid: role.functional-consultant 
summary: | 
  Les Consultants Fonctionnels tirent parti de Microsoft Dynamics 365 et de Microsoft Power Platform pour anticiper et planifier les besoins des clients.
subTitle: Les Consultants Fonctionnels tirent parti de Microsoft Dynamics 365 et de Microsoft Power Platform pour anticiper et planifier les besoins des clients.
certificationPaths: 
- title: Dynamics 365 Customer Service Functional Consultant
  linkedInKeywords: Dynamics 365 Customer Service Functional Consultant
  uid: certification-path.d365-functional-consultant-customer-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
    
- title: Dynamics 365 Field Service Functional Consultant
  linkedInKeywords: Dynamics 365 Field Service Functional Consultant
  uid: certification-path.d365-functional-consultant-field-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate

- title: Dynamics 365 Finance Functional Consultant
  linkedInKeywords: Dynamics 365 Finance Functional Consultant
  uid: certification-path.d365-functional-consultant-financials 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate


- title: Dynamics 365 Manufacturing Functional Consultant
  linkedInKeywords: Dynamics 365 Manufacturing Functional Consultant
  uid: certification-path.d365-functional-consultant-manufacturing
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate

- title: Dynamics 365 Marketing Functional Consultant
  linkedInKeywords: Dynamics 365 Marketing Functional Consultant
  uid: certification-path.d365-functional-consultant-marketing 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate

- title: Dynamics 365 Sales Functional Consultant
  linkedInKeywords: Dynamics 365 Sales Functional Consultant
  uid: certification-path.d365-functional-consultant-sales 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate

- title: Dynamics 365 Supply Chain Management Functional Consultant
  linkedInKeywords: Dynamics 365 Supply Chain Management Functional Consultant
  uid: certification-path.d365-functional-consultant-supply-chain-management
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate

certifications:
- uid: certification.d365-functional-consultant-customer-service
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-230  

- uid: certification.d365-functional-consultant-field-service
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-240

- uid: certification.d365-functional-consultant-financials
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-310  


- uid: certification.d365-functional-consultant-manufacturing
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-320  

- uid: certification.d365-functional-consultant-marketing
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-220  

- uid: certification.d365-functional-consultant-sales
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-210  

- uid: certification.d365-functional-consultant-supply-chain-management
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-330  
- uid: certification.power-platform-functional-consultant-associate
  requiredExams:
  - uid: exam.pl-200  
- uid: certification.d365-business-central-functional-consultant-associate
  requiredExams:
  - uid: exam.mb-800
resources:
- title: Guide de Formation et de Certification Microsoft
  description: Découvrez toutes les certifications dans un guide de formation et de certification concis.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Affiche de Formation et de Certification
  description: Choisissez la voie de la réussite avec cette affiche de formation et de certification.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Aide à la certification
  href: ../help.md
  description: Obtenez de l’aide à travers nos Forums de support de Microsoft Certification. Un modérateur du forum répondra sous 24 heures (du lundi au vendredi).
